### PR TITLE
Update Chinese localization

### PR DESCRIPTION
**Pull request by zhangyuesai**
Hi! With this pull request, I'd like to complete and improve Chinese translation for version 1.6.0.

Thanks for this helpful tool!

### CODE REVIEW

**Comment by yalov** [comment]
thanks

**Comment by yalov** [comment]
hi, I have added 3 new lines to localization

**Comment by zhangyuesai** [comment]
Translation for the new lines would be like:
```
#SpeedUnitAnnex_surfaceSpeedSplitNo          = 不分解 // No
#SpeedUnitAnnex_surfaceSpeedSplitLander		 = 只用于下降中的着陆器 // Only descending landers
#SpeedUnitAnnex_surfaceSpeedSplitAlways		 = 始终 // Always
```

Should I open a new PR for this?

**Comment by yalov** [comment]
no, I can copypaste it

**Pull request merged**
