### PR TITLE
Fixed german language tag

### PR DESCRIPTION
**Pull request by n116-software**

### CODE REVIEW

**Comment by yalov** [comment]
Can you also update German translation? There was few changes in en-us.cfg

**Comment by n116-software** [comment]
done

**Comment by yalov** [comment]
@Nils277  

also
```
#SpeedUnitAnnex_orbitEVA           = display name (EVA)
#SpeedUnitAnnex_orbitEVA_toolTip   = Display kerbal name for EVA instead of Apoapsis and Periapsis
#SpeedUnitAnnex_orbitTime          = display time to Ap/Pe
#SpeedUnitAnnex_orbitTime_toolTip  = Display time to the next apsis (Ap or Pe)
```

**Comment by n116-software** [comment]
Oh sorry missed that. Will do ;-)

**Comment by n116-software** [comment]
done

**Comment by yalov** [comment]
thanks 👍

**Pull request merged**
